Docs/general update nov2023
neicnordic/neic-sda pull request #67
Opened 2023-11-13 18:54 UTC by blankdots

### Describe the pull request:

- [x] Bug fix
- [x] Documentation change

### Pull request long description:

### Changes made:

- update links for `sda-*` repositories

2023-11-14 07:02 UTC, kjellp approved these changes
LGTM overall. Was a bit unsure about the "sensitive-data-archive/tree/main/<component>" paths?  And the use of tags to separate/run different microsevices from the same overall image (thought there will be a few different images, and a specific cmd/servicename to be provided in combination with the right image).

2023-11-14 07:36 UTC, blankdots commented
> Was a bit unsure about the "sensitive-data-archive/tree/main/" paths?

not sure how else to reference those, but we can fix in the next iteration 

> And the use of tags to separate/run different microsevices from the same overall image

we can bring that up in our bi-weekly, however that is something already existing and i just used that

2023-11-14 09:53 UTC, jbygdell requested changes

2023-11-14 09:53 UTC, jbygdell commented on README.md
> +| inbox         | SFTP, S3 or HTTPS server, acting as a dropbox, where user credentials are fetched from CentralEGA or via LifeScience AAI. [s3inbox](https://github.com/neicnordic/sensitive-data-arch
```suggestion
| inbox         | SFTP, S3 or HTTPS server, acting as a dropbox, where user credentials are fetched from CentralEGA or via LifeScience AAI. [s3inbox](https://github.com/neicnordic/sensitive-data-archive/tree/main/sda/cmd/s3inbox/s3inbox.md) or [sftp-inbox](https://github.com/neicnordic/sensitive-data-archive/tree/main/sda-sftp-inbox/README.md) |
```

2023-11-14 09:53 UTC, jbygdell commented on README.md
> +| download      | Provides a download/data access API for streaming (decrypted) archived data - source at: https://github.com/neicnordic/sda-download |
```suggestion
| download      | Provides a download/data access API for streaming (decrypted) archived data - source at: [https://github.com/neicnordic/sensitive-data-archive](https://github.com/neicnordic/sensitive-data-archive/tree/main/sda-download/README.md) |
```

2023-11-14 09:53 UTC, jbygdell commented on docs/deploy.md
> +- `ghcr.io/neicnordic/sensitive-data-archive:<version>-<service>` - where `<service>` corresponds to services such as: `finalize`, `ingest`, `intercept`, `verify`, `mapper`, `download`, `s3inbox`, `a
```suggestion
- `ghcr.io/neicnordic/sensitive-data-archive:<version>-auth` - authentication service
- `ghcr.io/neicnordic/sensitive-data-archive:<version>-download` - download service
- `ghcr.io/neicnordic/sensitive-data-archive:<version>` - all other services such as: `finalize`, `ingest`, `intercept`, `verify`, `mapper` and `s3inbox`
```

2023-11-14 10:56 UTC, jbygdell approved these changes

2023-11-15 19:59 UTC, aaperis approved these changes
Looks good! small suggestions to (possibly) improve clarity :-)

2023-11-15 19:59 UTC, aaperis commented on docs/connection.md
> +The message sent from the `finalize` to the `completed` queue.
```suggestion
The message sent from the `finalize` service to the `completed` queue.
```

2023-11-15 19:59 UTC, aaperis commented on docs/deploy.md
> +The following container image is used in the deployments `neicnordic/sensitive-data-archive`, provides the SDA services as well as PostgreSQL and RabbitMQ configuration. The tag is what separates the
```suggestion
`neicnordic/sensitive-data-archive`, provides the SDA services as well as PostgreSQL and RabbitMQ configuration. The following container image is used in the deployments where the tag separates between services:
```

2023-11-16 18:23 UTC, merged