Updated guide/deploy-k8s: dns name, ingress and network policies
neicnordic/neic-sda pull request #72
Opened 2023-11-21 22:13 UTC by tuzov

### Describe the pull request:

- [x] Documentation change

### Pull request long description:

Described dns name, service and ingress; Provided a basic example of network policy to allow ingress.

2023-11-22 16:09 UTC, tuzov commented on docs/guides/deploy-k8s.md
> +    ```
You're right, I got it vice versa. It should be three separate network-policies for every pod. for example,
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-inbox-service
spec:
  podSelector: 
    matchLabels:
      app: sda-svc-inbox
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
  policyTypes:
    - Ingress
```

Do we need to provide examples of network policies for the handbook? 
Currently we have got three network policies: namespace-isolation, postgres-operator and allow-ingress-outside-cluster. Postgres operator is our setup specific, maybe namespace-isolation and allow-ingress-outside-cluster might be useful to have in the docs.

2023-11-23 07:13 UTC, blankdots approved these changes
small improvement suggestions to point to k8s docs, other than that lgtm

2023-11-23 07:13 UTC, blankdots commented on docs/guides/deploy-k8s.md
> +   When deploying applications on Kubernetes, it is essential to understand the DNS naming conventions and ingress configurations for Pods and Services. Each Pod within the cluster is assigned a DNS
```suggestion
   When deploying applications on Kubernetes, it is essential to understand the DNS naming conventions and ingress configurations for [Pods](https://kubernetes.io/docs/concepts/workloads/pods/) and [Services](https://kubernetes.io/docs/concepts/services-networking/service/). Each Pod within the cluster is assigned a [DNS name](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/) in the format of `pod-ip-address.<cluster>.pod.cluster.local`. This DNS resolution allows seamless communication between Pods within the same cluster.
```

2023-11-23 07:13 UTC, blankdots commented on docs/guides/deploy-k8s.md
> +    Certain services, such as `inbox`, `download`, and `auth`, are configured to expect an ingress. Ingress provides external access to these services, allowing external clients to communicate with t
```suggestion
    Certain services, such as `inbox`, `download`, and `auth`, are configured to expect an ingress. [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) provides external access to these services, allowing external clients to communicate with them. The following services specifically expect an ingress:
```

2023-11-23 07:13 UTC, blankdots commented on docs/guides/deploy-k8s.md
> +    In addition, Kubernetes allows you to define Network Policies to control the communication between Pods. Network Policies are crucial for enforcing security measures within your cluster. They ena
```suggestion
    In addition, Kubernetes allows you to define [Network Policies](https://kubernetes.io/docs/concepts/services-networking/network-policies/) to control the communication between Pods. Network Policies are crucial for enforcing security measures within your cluster. They enable you to specify which Pods can communicate with each other and define rules for ingress and egress traffic.
```

2023-12-13 12:41 UTC, tuzov commented on docs/guides/deploy-k8s.md
> +    Certain services, such as `inbox`, `download`, and `auth`, are configured to expect an ingress. Ingress provides external access to these services, allowing external clients to communicate with t
done

2023-12-13 12:41 UTC, tuzov commented on docs/guides/deploy-k8s.md
> +   When deploying applications on Kubernetes, it is essential to understand the DNS naming conventions and ingress configurations for Pods and Services. Each Pod within the cluster is assigned a DNS
done

2023-12-13 12:41 UTC, tuzov commented on docs/guides/deploy-k8s.md
> +    In addition, Kubernetes allows you to define Network Policies to control the communication between Pods. Network Policies are crucial for enforcing security measures within your cluster. They ena
done

2023-12-13 14:00 UTC, jbygdell requested changes
Your `namespace-isolation` does actually allow ingress from anything that gets routed through the ingress controller.

2023-12-13 14:00 UTC, jbygdell commented on docs/guides/deploy-k8s.md
> +    ```
```suggestion

    ```yaml
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: namespace-isolation
    spec:
      podSelector: {}
      policyTypes:
      - Egress
      - Ingress
      egress:
      - to:
        - podSelector: {}
      - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
        ports:
          - port: 53
            protocol: UDP
          - port: 53
            protocol: TCP
      ingress:
        - from:
          - podSelector: {}
    ```
    ```yaml
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: inbox-ingress-with-ingress-controller
    spec:
      podSelector: 
          matchLabels:
          app: sda-svc-inbox
      ingress:
      - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: controller
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: controller
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx-direct
      policyTypes:
      - Ingress
    ```
    ```yaml
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
        name: inbox-ingress-with-nodeport
    spec:
        podSelector: 
            matchLabels:
            app: sda-svc-inbox
        ingress:
        - from:
            - ipBlock:
                cidr: 0.0.0.0/0
        policyTypes:
        - Ingress
    ```
```

2023-12-18 12:14 UTC, jbygdell approved these changes

2023-12-18 12:27 UTC, merged